name: pluto_os_system_config
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.4.0
  # yaru: ^8.3.0
  yaru:
    path: /code/PlutoDevelopment/PlutoOS-Monorepo/pluto_black_theme/
  flutter_svg: ^2.0.10+1
  plutoos_system_library:
    path: /code/PlutoDevelopment/PlutoOS-Monorepo/plutoos_system_library/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ubuntu_logo.svg
    - assets/arch_logo.svg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Regular.ttf